apiVersion: v1
kind: Pod
metadata:
  name: cotb2018
spec:
  containers:
  - name: cotb2018
    image: cotb2018:1.0.0
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 3
    readinessProbe:
      httpGet:
        path: /readyz
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 3